### ISSUE TITLE
Is it possible to use this repository to build new German themes for Dada Mail?

### ISSUE THREAD

**Issue by frederickjh** [holzhannes/dada_mail_foundation_email_templates-de-formal#1]
Hi!
I have been struggling to get a new German theme to inline the CSS (build). I have used the translations from this repository.

I have been following the instructions found [here on the Dada Mail website](https://dadamailproject.com/support/documentation-11_10_1/features-email_themes.pod.html#Create-a-New-Email-Theme-Using-the-Foundation-for-Emails-Workflow). Which refers to the [Foundation Sass instructions](https://get.foundation/emails/docs/sass-guide.html).

Using the [current default English Dada Mail theme](https://github.com/justingit/dada_mail_foundation_email_templates/archive/v11_10_1-stable_2020_03_24.tar.gz) and copying it into the new email theme created with Foundation for Emails will inline the CSS with `npm run build`. 

However when I  create a new email theme and  instead copy [this repository](https://github.com/holzhannes/dada_mail_foundation_email_templates-de-formal) into it, and then try to build using the `npm run build` command. It errors out. From the log starting just before the error:

>[10:24:29] Finished 'images' after 242 ms
[10:24:29] Starting 'inline'...
[10:24:31] 'inline' errored after 1.27 s
[10:24:31] Error in plugin "gulp-inline-css"
Message:
    Parse Error: <! - tmpl_var num_subscribers -> Abonnenten.

(The rest of the HTML of `admin_subscription_notice_message.html` was removed to remove noise from this post)

>Details:
    fileName: /var/www/docroot/themename-de/dist/admin_subscription_notice_message.html
    domainEmitter: [object Object]
    domainThrown: false
>
>[10:24:31] 'build' errored after 3.17 s
[10:24:31] 'default' errored after 3.17 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foundation-emails-template@1.0.0 build: `gulp --production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foundation-emails-template@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>
>npm ERR! A complete log of this run can be found in:
npm ERR!     /home/docker/.npm/_logs/2020-05-07T08_24_31_175Z-debug.log

<details><summary>CLICK ME to see or hide the text of 2020-05-07T08_24_31_175Z-debug.log</summary>
<p>

```bash
0 info it worked if it ends with ok
1 verbose cli [ '/home/docker/.nvm/versions/node/v11.15.0/bin/node',
1 verbose cli   '/home/docker/.nvm/versions/node/v11.15.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.7.0
3 info using node@v11.15.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle foundation-emails-template@1.0.0~prebuild: foundation-emails-template@1.0.0
6 info lifecycle foundation-emails-template@1.0.0~build: foundation-emails-template@1.0.0
7 verbose lifecycle foundation-emails-template@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle foundation-emails-template@1.0.0~build: PATH: /home/docker/.nvm/versions/node/v11.15.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/docroot/themename-de/node_modules/.bin:/home/docker/.pyenv/shims:/home/docker/.pyenv/bin:/home/docker/.rvm/gems/ruby-2.6.5/bin:/home/docker/.rvm/gems/ruby-2.6.5@global/bin:/home/docker/.rvm/rubies/ruby-2.6.5/bin:/home/docker/.yarn/bin:/home/docker/.config/yarn/global/node_modules/.bin:/home/docker/.nvm/versions/node/v11.15.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/docker/.composer/vendor/bin:/home/docker/.rvm/bin
9 verbose lifecycle foundation-emails-template@1.0.0~build: CWD: /var/www/docroot/themename-de
10 silly lifecycle foundation-emails-template@1.0.0~build: Args: [ '-c', 'gulp --production' ]
11 silly lifecycle foundation-emails-template@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle foundation-emails-template@1.0.0~build: Failed to exec build script
13 verbose stack Error: foundation-emails-template@1.0.0 build: `gulp --production`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/docker/.nvm/versions/node/v11.15.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:193:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/docker/.nvm/versions/node/v11.15.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:193:13)
13 verbose stack     at maybeClose (internal/child_process.js:999:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
14 verbose pkgid foundation-emails-template@1.0.0
15 verbose cwd /var/www/docroot/themename-de
16 verbose Linux 4.15.0-99-generic
17 verbose argv "/home/docker/.nvm/versions/node/v11.15.0/bin/node" "/home/docker/.nvm/versions/node/v11.15.0/bin/npm" "run" "build"
18 verbose node v11.15.0
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 1
22 error foundation-emails-template@1.0.0 build: `gulp --production`
22 error Exit status 1
23 error Failed at the foundation-emails-template@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

</p>
</details>

How can I create a new German theme using the German translations?

 I can edit the sass files and serve them up with `foundation watch`, so I have been able to create a new theme just not inline it so it can be used with Dada Mail.

Also, I had some issues with Nodejs. I ended up using version 7 based on [this comments in this issue](https://github.com/foundation/foundation-emails/issues/964#issuecomment-570334413). I had tried versions 12 and 10 before this. What version of Nodejs do you use for to build German Dada Mail themes?

Thanks in advance for any help you can give me!
Frederick

**Comment by frederickjh** [comment]
I also just noticed that there are more files in the English email templates `pages` folder than in the German ones in this repository. Runing a `diff` it appears the following are missing from this repository:

- `mailing_list_message-none.html`
- `mailing_list_message-none.txt`
- `mailing_list_message-old_school.html`
- `mailing_list_message-old_school.txt`
- `new_list_created_message.html`
- `new_list_created_message.txt`
- `you_are_already_subscribed_message.html`

` subscribed_by_list_owner_message.txt` is only in this repository.

**Comment by frederickjh** [comment]
I finally figured out how to make a new German theme.  

- I followed the [instructions to setup a new Foundations for Email project.](https://get.foundation/emails/docs/sass-guide.html)
- Copied the Dada Mail default theme from Github per [Dada Mail Documentation - Create a New Email Theme Using the Foundation for Emails Workflow](https://dadamailproject.com/support/documentation-11_10_1/features-email_themes.pod.html#Create-a-New-Email-Theme-Using-the-Foundation-for-Emails-Workflow)
[Latests version](https://github.com/justingit/dada_mail_foundation_email_templates/tarball/master)
[Earlier versions](https://github.com/justingit/dada_mail_foundation_email_templates/releases)
- Made my theme changes
- Build the theme
- Then translated the theme

I am guessing this is the correct workflow as trying to build a translated theme does not work and throws parsing errors.
